# Generated by Django 4.0.7 on 2023-01-12 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_created_at_product_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
    ]
