# Generated by Django 4.1.5 on 2023-01-12 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_product_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="amount",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
